# THIS IS THE SCRIPT USED AT BENDURA TO CHECK AUTOMATICALLY FOR AGENTS UPDATE PACKAGES
# IT CAN BE ADAPTED TO YOUR NEEDS. THE BASIC RULES TO FOLLOW ARE THE FOLLOWING:
# 1. EACH CUSTOMER HAS A DEDICATED FOLDER ON ZABBIX FOLDER WHICH CONTAINS THE NEW AGENT PACKAGES TO BE DEPLOYED
# 2. THIS SCRIPT CONNECTS TO ZABBIX SERVER AND RETRIEVES PACKAGE FILES FROM THE BENDURA FOLDER
# 3. THE PACKAGE FILES ARE STORED LOCALLY TO ADD PERMISSIONS AND THEN COPIED IN BENDURA'S CENTRAL REPOSITORY
# 4. THIS SCRIPT WILL REMOVE ANY PACKAGE FILES OLDER THAN 10 MINUTES FROM THE CENTRAL REPOSITORY

# 5. EACH AGENT WILL MONITOR THE CENTRAL REPOSITORY FOR NEW PACKAGE FILES
# 6. IF A PACKAGE IS FOUND, EACH AGENT COPIES THE PACKAGE TO THE LOCAL UPDATES DIRECTORY
# 7. ONCE A PACKAGE IS INSTALLED, THE PACKAGE FILE IS DELETED


#ZABBIX SERVER
SERVER=192.168.141.164
#ZABBIX USER
USER=scpuser
#CUSTOMER PATH ON ZABBIX SERVER WHICH CONTAINS AGENTS UPDATES FILES
ZABBIX_UPDATES_PATH=/outputs/transfers/bendura/updates
#LOCAL DIRECTORY WHICH WILL RECEIVE THE NEW PACKAGE FROM ZABBIX
LOCAL_UPDATES_PATH=/export/home/nfs_monitoring/utils/updates
#CUSTOMER CENTRAL REPOSITORY WHICH WILL RECEIVE THE NEW PACKAGE
CENTRAL_UPATES_PATH=/monitoring/UPDATES

CURRENT_TIME=$(date +%H%M)

while [ "$CURRENT_TIME" -lt 2359 -a "$CURRENT_TIME" -gt 0005 ]; do
	CURRENT_TIME=$(date +%H%M)
  
  #DELETE ALL LOCAL AGENT PACKAGES THAT ARE OLDER THAN 10 MINUTES
  find ${CENTRAL_UPATES_PATH} -mmin +10 -type f -exec rm -f {} \; >> ~/log/updates_$(date +'%Y%m%d').log 2>&1	
	
  #CONNECT TO ZABBIX SERVER AND GO TO THE SPECIFIC CUSTOMER UPDATES DIRECTORY (ZABBIX_UPDATES_PATH)
  #RETRIEVE FILES AND STORE THEM IN LOCAL FOLDER FIRST
  #DELETE THE FILES FROM ZABBIX
  sftp $USER@$SERVER <<! >> ~/log/updates_$(date +'%Y%m%d').log 2>&1 
	cd ${ZABBIX_UPDATES_PATH} >> ~/log/updates_$(date +'%Y%m%d').log 2>&1 
	chmod -R 777 . >> ~/log/updates_$(date +'%Y%m%d').log 2>&1
	get * ${LOCAL_UPDATES_PATH} >> ~/log/updates_$(date +'%Y%m%d').log 2>&1 
	rm * >> ~/log/updates_$(date +'%Y%m%d').log 2>&1
	exit
!

  #SET THE APPROPRIATE RIGHTS TO THE NEW PACKAGE IN THE LOCAL DIRECTORY (LOCAL_UPDATES_PATH)
  #PUSH THE PACKAGES TO THE CUSTOMER CENTRAL REPOSITORY (CENTRAL_UPATES_PATH)
  #DELETE FILES FROM LOCAL DIRECTORY
	chmod -R 777 ${LOCAL_UPDATES_PATH} >> ~/log/updates_$(date +'%Y%m%d').log 2>&1 
	cp -f ${LOCAL_UPDATES_PATH}/* ${CENTRAL_UPATES_PATH}
	rm -f ${LOCAL_UPDATES_PATH}/*
	sleep 10
done 
